play_suggested:
  description: Play the suggested video from the specified program name
  target:
    entity:
      domain: media_player
      supported_features:
        - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: tv4_play
    program_id:
      required: true
      example: "67ff22880e988cd4d149"
      selector:
        text:
