name: Afternoon test

on:
  schedule:
    - cron: "30 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          tries=0
          until [ "$tries" -ge 5 ]
          do
            pytest custom_components/tv4_play/video_url_fetch/afternoon_test.py && break
            exit_code=$?
            tries=$((tries+1))
            sleep 60
          done
          exit $exit_code
